### ISSUE TITLE
Is this active?

### ISSUE THREAD

**Issue by internetboekhandel** [keesschepers/dhlparcelapi#2]
I need an api for connecting my website to dhlparcel.nl
This seems the only php project I can currently find.
But there is no documentation, and I couldn't install via composer (yet).

Can anyone tell if this is active (public) and how I can use this,

Thanx for any reply in advance.

With regards, Theo

**Comment by keesschepers** [comment]
Hello Theo,

Yes, it's definitly active! I am still working on it. But I am willing to help you to integrate it. And offcourse you are free to help us :)

Composer install should work, what error did you get?

**Comment by internetboekhandel** [comment]
This is the error:
 [InvalidArgumentException]
  Could not find package keesschepers/dhlparcelapi at any version for your minimum-stability (stable). Check the package spell
  ing or your minimum-stability

I tried:
composer require keesschepers/dhlparcelapi

I need this because I want to directly interact with DHL for making labels, currently we make an csv export and import this in my.dhlparcel.nl
This works ok, but I also need to enter the track en trace in a database, currently I have to do this manually.
As we getting more en more parcels automation is needed.

With regards, Theo

**Comment by internetboekhandel** [comment]
I have it installed with composer. 
adding this to composer.json worked:
 "minimum-stability": "dev",

but need some info on how to use it.

$dhl = new \Keesschepers\DhlParcelApi\DhlClient($userId, $key);
$label = $dhl->createLabel([
(with all data)

But I get a result as object, but cannot seem to get the barcode and pdf.
I saw you have some code for the pdf but I can't get it to work.

Keesschepers\DhlParcelApi\DhlParcel Object
(
    [labelId:Keesschepers\DhlParcelApi\DhlParcel:private] => f975ab61-3a18-4031-87d4-179f0c28dcf1
    [labelType:Keesschepers\DhlParcelApi\DhlParcel:private] => B2X_Generic_A4_Third
    [trackerCode:Keesschepers\DhlParcelApi\DhlParcel:private] => JVGL05871660733749634083
    [routingCode:Keesschepers\DhlParcelApi\DhlParcel:private] => 2LNL8442BG+04000000
    [userId:Keesschepers\DhlParcelApi\DhlParcel:private] => d0808212-8de1-4604-b69d-4a0f4274801b
    [organizationId:Keesschepers\DhlParcelApi\DhlParcel:private] => 9fa61111-d5da-44a2-838c-b116865ea81e
    [orderReference:Keesschepers\DhlParcelApi\DhlParcel:private] => myReference
    [pdfContent:Keesschepers\DhlParcelApi\DhlParcel:private] => JVBERi0xLjQ

**Comment by keesschepers** [comment]
You should use the `$label->getPdfContent()` method to obtain the PDF content.

Here an example from our application where we create serveral labels with:

	<?php

	namespace Polyestershoppen\ShippingBundle\Service;

	use Polyestershoppen\OrderBundle\Entity\Order;
	use Keesschepers\DhlParcelApi\DhlClient;
	use Ramsey\Uuid\Uuid;

	class DhlLabelFactory
	{
		/** @var \Keesschepers\DhlParcelApi\DhlClient */
		private $dhlApi;

		/** @var array */
		private $configuration;

		/**
		 * Constructor.
		 *
		 * @param \Keesschepers\DhlParcelApi\DhlClient $dhlApi
		 * @param array                                $configuration
		 */
		public function __construct(DhlClient $dhlApi, array $configuration)
		{
			$this->dhlApi = $dhlApi;
			$this->configuration = $configuration;
		}

		/**
		 * Returns default parameters for creating a parcel.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 *
		 * @return array
		 */
		private function getDefaultParameters(Order $order)
		{
			$uuid4 = Uuid::uuid4();

			return [
				'labelId' => $uuid4->toString(),
				'orderReference' => (string)$order->getId(),
				'parcelTypeKey' => 'SMALL',
				'receiver' => $this->createReceiver($order),
				'shipper' => $this->createShipper(),
				'accountId' => $this->configuration['account_id'],
				'options' => [
					['key' => 'DOOR'],
					['key' => 'REFERENCE', 'input' => (string)$order->getId()],
				],
				'returnLabel' => false,
				'pieceNumber' => 1,
				'quantity' => 1,
				'automaticPrintDialog' => false,
			];
		}

		/**
		 * Create a label and return a parcel.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 * @param array                                      $stockProducts
		 */
		public function createDhlForYouLabel(Order $order, array $stockProducts)
		{
			$shippingAddress = $order->getShippingAddress() ?: $order->getBillingAddress();

			$options = [
				['key' => 'DOOR'],
				['key' => 'REFERENCE', 'input' => (string)$order->getId()],
			];

			if ($shippingAddress->getCountry() == 'BE' && date('N') == 5) {
				$options[] = ['key' => 'S'];
			}

			$parameters = $this->getDefaultParameters($order);
			$parameters['parcelTypeKey'] = 'SMALL';
			$parameters['receiver']['address']['isBusiness'] = false;
			$parameters['options'] = $options;

			$label = $this->dhlApi->createLabel($parameters);

			return $label;
		}

		/**
		 * Create a evening label and return a parcel.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 * @param array                                      $stockProducts
		 */
		public function createDhlForYouEveningLabel(Order $order, array $stockProducts)
		{
			$shippingAddress = $order->getShippingAddress() ?: $order->getBillingAddress();

			$options = [
				['key' => 'DOOR'],
				['key' => 'EVE'],
				['key' => 'REFERENCE', 'input' => (string)$order->getId()],
			];

			$parameters = $this->getDefaultParameters($order);
			$parameters['parcelTypeKey'] = 'SMALL';
			$parameters['receiver']['address']['isBusiness'] = false;
			$parameters['options'] = $options;

			$label = $this->dhlApi->createLabel($parameters);

			return $label;
		}

		/**
		 * Create a evening label and return a parcel.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 * @param array                                      $stockProducts
		 */
		public function createDhlEuroPlusLabel(Order $order, array $stockProducts)
		{
			$shippingAddress = $order->getShippingAddress() ?: $order->getBillingAddress();

			$options = [
				['key' => 'DOOR'],
				['key' => 'REFERENCE', 'input' => (string)$order->getId()],
			];

			$parameters = $this->getDefaultParameters($order);
			$parameters['parcelTypeKey'] = 'MEDIUM';
			$parameters['receiver']['address']['isBusiness'] = true;
			$parameters['options'] = $options;

			$label = $this->dhlApi->createLabel($parameters);

			return $label;
		}

		/**
		 * Create a morning delivery label and returns a parcel.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 * @param array                                      $stockProducts
		 */
		public function createDhlExpressLabel(Order $order, array $stockProducts)
		{
			$shippingAddress = $order->getShippingAddress() ?: $order->getBillingAddress();

			$options = [
				['key' => 'DOOR'],
				['key' => 'EXP'],
				['key' => 'REFERENCE', 'input' => (string)$order->getId()],
			];

			$parameters = $this->getDefaultParameters($order);
			$parameters['parcelTypeKey'] = 'MEDIUM';
			$parameters['receiver']['address']['isBusiness'] = true;
			$parameters['options'] = $options;

			$label = $this->dhlApi->createLabel($parameters);

			return $label;
		}

		/**
		 * Creates the parameters necesarry for the receiver details.
		 *
		 * @param \Polyestershoppen\OrderBundle\Entity\Order $order
		 *
		 * @return array
		 */
		private function createReceiver(Order $order)
		{
			$shippingAddress = $order->getShippingAddress() ?: $order->getBillingAddress();

			$receiver = [
				'name' => [
					'firstName' => $shippingAddress->getFirstname(),
					'lastName' => $shippingAddress->getFullLastName(),
					'companyName' => $shippingAddress->getCompany(),
				],
				'address' => [
				  'countryCode' => $shippingAddress->getCountry(),
				  'postalCode' => strtoupper($shippingAddress->getPostalCode()),
				  'city' => $shippingAddress->getPlace(),
				  'street' => $shippingAddress->getStreet(),
				  'number' => $shippingAddress->getHouseNr(),
				  'isBusiness' => (null !== $shippingAddress->getCompany()),
				  'addition' => $shippingAddress->getHouseNrSuffix(),
				],
				'email' => $order->getCustomer()->getEmail(),
				'phoneNumber' => $order->getCustomer()->getPhone(),
			];

			return $receiver;
		}

		/**
		 * Creates the parameters necesarry for sending the shipper details.
		 *
		 * @return array
		 */
		private function createShipper()
		{
			return [
				'name' => [
				  'companyName' => $this->configuration['company'],
				],
				'address' => [
				  'countryCode' => $this->configuration['country'],
				  'postalCode' => $this->configuration['postalcode'],
				  'city' => $this->configuration['city'],
				  'street' => $this->configuration['street'],
				  'number' => $this->configuration['housenumber'],
				  'isBusiness' => true,
				],
				'email' => $this->configuration['email'],
				'phoneNumber' => (string)$this->configuration['phone'],
			];
		}
	}

**Comment by internetboekhandel** [comment]
Thanx!

This works, I can use your project now to make dhl labels.
The example was solving the problems I had.

With regards, Theo
